default: &default
  secret_key_base: 7e23900d5e00b1314e98a3127f10428196a9136172ae1f9faf943eff0c1cb6602c45eccf57dd92c77d782317cdd53e55e71e85074a2864e1175f2a04be76e407
  BASIC_AUTH_USERNAME: test
  BASIC_AUTH_PASSWORD: test
  DATABASE_IP: 192.168.33.10
  DATABASE_USERNAME: dev_db_user
  DATABASE_PASSWORD: super_secret


development: *default

test:
  <<: *default

acceptance: *default

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
